package com.aiken.pos.admin.constant;

/**
 * Event Types
 *
 * @author Asela Liyanage
 * @version 1.0
 * @since 2021-08-09
 */
public interface EventTypes {

    String AUTO_SETTLE = "AUTO_SETTLE";
    String FORCE_SETTLE = "FORCE_SETTLE";
    String NO_SETTLE = "NO_SETTLE";
    String CLEAR_BATCH = "CLEAR_BATCH";
    String NAME_CHANGE = "NAME_CHANGE";
    String ADDRESS_CHANGE = "ADDRESS_CHANGE";
    String QR_PARAM_CHANGE = "QR_PARAM_CHANGE";
    String QR_MID_TID_CHANGE = "QR_MID_TID_CHANGE";
    String ECR_SALE = "ECR_SALE";
    String ECR_QR = "ECR_QR";
    String MANUAL_KEY_IN = "MANUAL_KEY_IN";
    String MANUAL_KEY_IN_AMEX_ONLY = "MANUAL_KEY_IN_FOR_AMEX";
    String ADD_EPP = "ADD_EPP";
    String DELETE_EPP = "DELETE_EPP";
    String DIGITAL_SIGNATURE = "DIGITAL_SIGNATURE";
    String DEBUG_MODE = "DEBUG_MODE";
    String ACTIVITY_TRACKER = "ACTIVITY_TRACKER";
    String ACTIVITY_REPORT = "ACTIVITY_REPORT";
    String QR_REFUND = "QR_REFUND";
    String REVERSAL_HISTORY = "REVERSAL_HISTORY";
    String PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
    String ADD_PROFILE = "ADD_PROFILE";
    String REMOVE_PROFILE = "REMOVE_PROFILE";
    String MODIFY_PROFILE = "MODIFY_PROFILE";
    String ONE_CLICK_SETUP = "ONE_CLICK_SETUP";
    String SALE_MID_TID_CHANGE = "SALE_MID_TID_CHANGE";
    String EPP_MID_TID_CHANGE = "EPP_MID_TID_CHANGE";
    String AMEX_MID_TID_CHANGE = "AMEX_MID_TID_CHANGE";
    String EPP_AMEX_MID_TID_CHANGE = "EPP_AMEX_MID_TID_CHANGE";
    String QR_VID_CID_CHANGE = "QR_VID_CID_CHANGE";
    String CONFIG_AMEX = "CONFIG_AMEX";
    String SALE_DCC = "CONFIG_SALE_DCC";
    String SALE_OFFLINE = "CONFIG_SALE_OFFLINE";
    String SALE_PRE_AUTH = "CONFIG_SALE_PRE_AUTH";
    String AMEX_DCC = "CONFIG_AMEX_DCC";
    String AMEX_OFFLINE = "CONFIG_AMEX_OFFLINE";
    String AMEX_PRE_AUTH = "CONFIG_AMEX_PRE_AUTH";
    String BIN_BLOCK_CONFIG = "BIN_BLOCK_CONFIG";
    String CLEAR_REVERSAL = "CLEAR_REVERSAL";
    String AUTO_REVERSAL = "AUTO_REVERSAL";
    String CONFIG_AUTH_SERVER = "CONFIG_AUTH_SERVER";
    String NETWORK_MODE_CHANGE = "NETWORK_MODE_CHANGE";
    String PRINTLESS = "PRINTLES";
    String DISABLE_FRGN_PMNTS_FOR_LKR_CARDS = "DISABLE_FRGN_PMNTS_FOR_LKR_CARDS";
    String VOID_AND_SETTLEMENT_PASSWORD = "VOID_AND_SETTLEMENT_PASSWORD";
    String DIFFERENT_MID_TID_SETTINGS = "DIFFERENT_MID_TID_SETTINGS";
    String MANUAL_KEY_IN_FOR_PRE_AUTH = "MANUAL_KEY_IN_FOR_PRE_AUTH";
    String MANUAL_KEY_IN_FOR_OFFLINE = "MANUAL_KEY_IN_FOR_OFFLINE";
    String SIGNATURE_PIN_PRIORITY = "SIGNATURE_PIN_PRIORITY";
    String BLOCK_MAG_TRANSACTIONS = "BLOCK_MAG_TRANSACTIONS";
    String ENABLE_CUSTOMER_RECEIPT = "ENABLE_CUSTOMER_RECEIPT";
    String DISABLE_JCB_TRANSACTIONS = "ENABLE_CUSTOMER_RECEIPT";
    String SALE_JCB = "ENABLE_SALE_JCB";
    String ENABLE_IMEI_SCAN = "ENABLE_IMEI_SCAN";
    String ENABLE_COMMISSION_RATE = "ENABLE_COMMISSION_RATE";
    String CONFIGURE_OFFLINE_USERS = "CONFIGURE_OFFLINE_USERS";
    String ENABLE_SANHINDA_PAYMENTS = "ENABLE_SANHINDA_PAYMENTS";
    String ONE_TIME_SETTING_PASSWORD = "ONE_TIME_SETTING_PASSWORD";
    String ENABLE_REFERENCE_DATA = "ENABLE_REFERENCE_DATA";
    String ENABLE_TLE_PROFILE = "ENABLE_TLE_PROFILE";

    //Extended Event types for 'SALE_MID_TID_CHANGE' Event
    String NA = "NA";
    String SALE = "SALE";
    String SALE_VISA = "SALE_VISA_ONLY";
    String SALE_MASTER = "SALE_MASTER_ONLY";
    String SALE_JCB_CUP = "SALE_JCB_CUP";
    String SALE_OTHER = "SALE_OTHER";
    String EVENT_AUTO_UPDATE = "EVENT_AUTO_UPDATE";


    //ExecuteTypes
    String AUTO_UPDATE = "AUTO";
    String MANUAL_UPDATE = "MANUAL";


}
